import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CubeLogo } from "@/components/cubeLogo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-black" lang="en">
      <body className={inter.className}>=
        <div className="ml-72 mt-10">
          <CubeLogo />
          <span className="text-white text-4xl font-extrabold absolute top-16 left-80 pl-5">WebVault</span>
        </div>
        {children}
      </body>
    </html>
  );
}
